Earlier today, the Nautilus DevOps team deployed a new release for an application. However, a customer has reported a bug related to this recent release. Consequently, the team aims to revert to the previous version.


There exists a deployment named nginx-deployment; initiate a rollback to the previous revision.

Note: The kubectl utility on jump_host is configured to interact with the Kubernetes cluster.


 Step 1: Check rollout history

First, confirm that multiple revisions exist:

kubectl rollout history deployment nginx-deployment

You’ll see something like:

deployment.apps/nginx-deployment 
REVISION  CHANGE-CAUSE
1         <none>
2         kubectl set image deployment/nginx-deployment ...

Step 2: Roll back to the previous revision

Simply run:

kubectl rollout undo deployment nginx-deployment

If you want to roll back to a specific revision (say revision 1):

kubectl rollout undo deployment nginx-deployment --to-revision=1


Step 3: Verify the rollback

Monitor rollout status:

kubectl rollout status deployment nginx-deployment


Then check the image version:
kubectl describe deployment nginx-deployment | grep Image:

